In [2]:
import pandas as pd

In [29]:
df=pd.read_csv('C:/Users/Ibscai11.DGVC-MCA/iris.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           NaN          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          NaN           1.4          0.2  Iris-setosa

In [30]:
df.isnull().sum()

sepal_length    2
sepal_width     2
petal_length    1
petal_width     0
class           0
dtype: int64

In [31]:
df['sepal_length']=df['sepal_length'].fillna(0)

In [34]:
df.isnull().sum()

sepal_length    0
sepal_width     2
petal_length    1
petal_width     0
class           0
dtype: int64

In [33]:
mn=df['sepal_width'].mean()
mn

3.0513513513513515

In [35]:
df['sepal_width']=df['sepal_width'].fillna(mn)

In [44]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    1
petal_width     0
class           0
dtype: int64

In [57]:
md=df['petal_length'].median()
md

4.4

In [58]:
df['petal_length']=df['petal_length'].fillna(md)

In [59]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

In [55]:
ms=df['petal_width'].mode()
ms

0    0.2
Name: petal_width, dtype: float64

In [56]:
df['petal_width']=df['petal_width'].fillna(ms)

In [54]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    1
petal_width     0
class           0
dtype: int64

In [3]:
df=pd.read_csv('C:/Users/Ibscai11.DGVC-MCA/AirQualityUCI.csv')
df.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,10-03-2004,18:00:00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10-03-2004,19:00:00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10-03-2004,20:00:00,NaN,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10-03-2004,21:00:00,2.2,NaN,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10-03-2004,22:00:00,1.6,1272.0,NaN,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

In [4]:
df.isnull().sum()

Date             0
Time             0
CO(GT)           2
PT08.S1(CO)      2
NMHC(GT)         2
C6H6(GT)         2
PT08.S2(NMHC)    2
NOx(GT)          2
PT08.S3(NOx)     2
NO2(GT)          2
PT08.S4(NO2)     2
PT08.S5(O3)      2
T                2
RH               2
AH               1
dtype: int64

In [5]:
df['CO(GT)']=df['CO(GT)'].fillna(0)

In [66]:
df.isnull().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      2
NMHC(GT)         2
C6H6(GT)         2
PT08.S2(NMHC)    2
NOx(GT)          2
PT08.S3(NOx)     2
NO2(GT)          2
PT08.S4(NO2)     2
PT08.S5(O3)      2
T                2
RH               2
AH               1
dtype: int64

In [6]:
mn=df['PT08.S1(CO)'].mean()
mn

1048.8773917691074

In [7]:
df['PT08.S1(CO)']=df['PT08.S1(CO)'].fillna(mn)

In [8]:
df.isnull().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         2
C6H6(GT)         2
PT08.S2(NMHC)    2
NOx(GT)          2
PT08.S3(NOx)     2
NO2(GT)          2
PT08.S4(NO2)     2
PT08.S5(O3)      2
T                2
RH               2
AH               1
dtype: int64

In [11]:
md=df['C6H6(GT)'].median()
md

7.9

In [12]:
df['C6H6(GT)']=df['C6H6(GT)'].fillna(md)

In [13]:
df.isnull().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         2
C6H6(GT)         0
PT08.S2(NMHC)    2
NOx(GT)          2
PT08.S3(NOx)     2
NO2(GT)          2
PT08.S4(NO2)     2
PT08.S5(O3)      2
T                2
RH               2
AH               1
dtype: int64

In [19]:
ms=df['NOx(GT)'].mode()[0]
ms

-200.0

In [20]:
df['NOx(GT)']=df['NOx(GT)'].fillna(ms)

In [21]:
df.isnull().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         2
C6H6(GT)         0
PT08.S2(NMHC)    2
NOx(GT)          0
PT08.S3(NOx)     2
NO2(GT)          0
PT08.S4(NO2)     2
PT08.S5(O3)      2
T                2
RH               2
AH               1
dtype: int64

In [22]:
df["NO2(GT)"] = df["NO2(GT)"].ffill()
df["PT08.S5(O3)"] = df["PT08.S5(O3)"].bfill()

In [23]:
df.isnull().sum()

Date             0
Time             0
CO(GT)           0
PT08.S1(CO)      0
NMHC(GT)         2
C6H6(GT)         0
PT08.S2(NMHC)    2
NOx(GT)          0
PT08.S3(NOx)     2
NO2(GT)          0
PT08.S4(NO2)     2
PT08.S5(O3)      0
T                2
RH               2
AH               1
dtype: int64